# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plum < Formula
  desc "Claude Plugin Manager - Discover and install plugins from 10+ marketplaces"
  homepage "https://github.com/itsdevcoffee/plum"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.2/plum_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "d37871dbd2a88d1a01d8f48a4c60913f8319d8571dd8366c1534e9c75e330bf3"

      def install
        bin.install "plum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.2/plum_0.3.2_Darwin_arm64.tar.gz"
      sha256 "7b0391a249e85fea613e1b1c14ec88d8780237a230a36ce90e882dc784a095d7"

      def install
        bin.install "plum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.2/plum_0.3.2_Linux_x86_64.tar.gz"
      sha256 "d2ae7bb8946e4da115a799301f99639990246b05faa2c81b765612e6a641a38f"
      def install
        bin.install "plum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.2/plum_0.3.2_Linux_arm64.tar.gz"
      sha256 "a1159783989449f91e8d39686c7c091fac85f8787521f9e318c1a8d6c4172895"
      def install
        bin.install "plum"
      end
    end
  end

  test do
    system "#{bin}/plum", "--version"
  end
end
