# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plum < Formula
  desc "Claude Plugin Manager - Discover and install plugins from 10+ marketplaces"
  homepage "https://github.com/itsdevcoffee/plum"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.4/plum_0.3.4_Darwin_x86_64.tar.gz"
      sha256 "702befb5d0266926ce60e4f85a38f29527c11fae12fd0ddcdc49d7a41eedaac0"

      def install
        bin.install "plum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.4/plum_0.3.4_Darwin_arm64.tar.gz"
      sha256 "74a08615353dc4b0e763f90d0e63500a0c3faaabf39eacb8e245b8defabb2ff7"

      def install
        bin.install "plum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.4/plum_0.3.4_Linux_x86_64.tar.gz"
      sha256 "e0b28abb9981f52516c5f17e8dea6254347f1017ff3d34141bcc9f0b2a514069"
      def install
        bin.install "plum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itsdevcoffee/plum/releases/download/v0.3.4/plum_0.3.4_Linux_arm64.tar.gz"
      sha256 "19eee724e5ea18c90f22083c3b0804f2ef3dd2b371f6fb2562245a6aea1f7dc6"
      def install
        bin.install "plum"
      end
    end
  end

  test do
    system "#{bin}/plum", "--version"
  end
end
